Update Lecture

diff --git a/Lecture b/Lecture
--- a/Lecture
+++ b/Lecture
@@ -52,7 +52,10 @@ DAY 1
     /bin/bash
     
     find /var/log -iname "*.log" -prntf '%f' 2> /dev/null   *** finds all files in /var/log that end in '.log'
-    
+
+
+
+
 DAY 2
     
     awk -F: '{print $1,$3}' /etc/passwd               *** prints first and third items after delimiter ':', can be in any order ex. $3,$1
@@ -62,7 +65,7 @@ DAY 2
                              ^^--'BEGIN {OFS="#"}'    *** changes field delimiter to # when it prints output
     tail /etc/passwd | awk -F: '{print $3}' | sort -n *** sorts (alpha)numerically, -nr to sort descending
     | sort -u                                         *** only prints duplicates once
-    cat ____ | awk '{print $1}' | soer -nr | uniq -c  *** prints n reverse alphanumeric order, and shows the number of duplicates
+    cat ____ | awk '{print $1}' | sort -nr | uniq -c  *** prints n reverse alphanumeric order, and shows the number of duplicates
     
     tail /etc/passwd > sedpasswd.txt
     sed 's/home/nobodyhome/g' sedpasswd.txt            *** substitutes home with nobodyhome, g makes it run on every occurance, without g it only runs on the first
@@ -72,4 +75,88 @@ DAY 2
     sed 's/:x:/ /' file.txt                            *** replaces :x: with ' '
     sed -e '/^c/d' -e 's/nobodyhome/home/' file.txt    *** -e runs first expression then runs second expression on matched lines ** mini pipe
     sed '/^c/d';'s/nobodyhome/home/' file.txt          *** same thing as above
+
+
+
+
+DAY 3
+    ~.bashrc                                           *** to make alias permanent
+    A=100     ** echo $A                               *** sets variable A to value 100
+            #!/bin/bash
+            
+            echo "Nuumber of arguments passed: $# " 
+            echo "Script name is $0 "
+            echo "The 2nd argument passed is $2 "
+            echo "Arguments passed to script: $* "
+            echo "Exit status of last command that executed: $? "
+            echo "Last argument provided to previous command: $_ "
+            echo "PID of current shell is $$ "
+            echo "Flags are set in the shell: $- "
+            
+            * 0
+            * ./demo.sh
+            *
+            *
+            * 0
+            * 0
+            * 19549
+            * hB
+            
+            
+            #!/bin/bash
+            
+            function name () {
+                    commands
+            }
+            
+            function_name            
     
+    
+            
+            
+            function test_shadow () {
+            if [[ -e /etc/shadow ]] ;
+            then
+                    echo "Shadow exists"
+            else 
+                    echo "Shadow is missing"
+            fi
+            }
+            
+            function test_passwd () {
+            if [[ -e /etc/passwd ]] ;
+            then
+                    echo "passwd exists"
+            else
+                    echo "passwd is mssing"
+            fi
+            }
+            
+            
+            test_shadow
+            test_passwd
+            
+            
+            ./demo2.sh
+            Shadow exists
+            passwd exists
+            
+            
+      student:~Desktop$ function do_stuff () {
+      > date
+      > echo "i like boys"
+      > ls 
+      > }
+      
+      student:~Desktop$ do_stuff
+      Thu May  5 13:44:14 UTC 2022
+      i like boys
+      1123   1145,  Desktop    Music     Templates  git         peda               shadow.txt
+      1123,  1156   Documents  Pictures  Videos     monkey.py   python             test
+      1134,  CUT    Downloads  Public    bash       msfinstall  school_prompt.txt  test1
+      
+      
+      
+      md5sum MBRcopy                                      *** returns md5 hash of MBRcopy file, cannot do to directories
+      echo ~/Desktop/MBRcopy | md5sum                     *** returns hash of the piped string
+      
